version = 1

[[annotations]]
path = [
 ".gitignore",
 "Makefile",
 "README.md",
 "bootmenu.asm",
 "doc/hposdump-c520.md",
 "doc/hposdump-c520.zip",
 "doc/hposdump-pal-lores-c520.png",
 "doc/hposdump-pal-lores-wuae.png",
 "images/choice.png",
 "images/choice.py",
 "images/header.png",
 "images/header.py",
]
SPDX-FileCopyrightText = "2025 Nico Bendlin <nico@nicode.net>"
SPDX-License-Identifier = "0BSD"

